### ISSUE TITLE
Requrest for further examples 

### ISSUE THREAD

**Issue by iliasmachairas** [DHI-GRAS/docker-sen2cor#2]
This repository is insightful.  Could you provide some examples running the docker with some parameters? Thanks in advance!

**Comment by j08lue** [comment]
There is very little to it. The container exposes the Sen2Cor `L2A_Process` script, so you just

```
docker build https://github.com/DHI-GRAS/docker-sen2cor.git -t sen2cor
docker run sen2cor --help
```

(have not tried this)

**Comment by j08lue** [comment]
It's just a wrapper for Sen2Cor's `L2A_Process`, so whatever you pass to that you can pass to this container. Just need to mount or copy in your data.

```
docker build https://github.com/DHI-GRAS/docker-sen2cor.git -t sen2cor
docker run sen2cor --help
```
